WRITE-HOST "*************************************"
WRITE-HOST "* DELETING DESKTOP SHORTCUTS *"
WRITE-HOST "*************************************"

Remove-Item "C:\Users\Public\Desktop\Acrobat Reader DC.lnk"
Remove-Item "C:\Users\Public\Desktop\Google Chrome.lnk"
WRITE-HOST " "
WRITE-HOST " "
WRITE-HOST "Complete... "
WRITE-HOST " "